{
    "openapi": "3.0.0",
    "info": {
        "title": "Mobills API",
        "version": "0.1"
    },
    "paths": {
        "/api/register/": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "description": "Create an account on application",
                "operationId": "8c28d866ae1606f9aa823e81f6e85e32",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "c_password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "success": true,
                                            "data": {
                                                "token": "r6V74GKLmwYzFAbK2DWd31X1LMo8qj",
                                                "name": "Cleverson"
                                            },
                                            "message": "User register successfully"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/api/login/": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "description": "Login on applicaton",
                "operationId": "984d26f827ec39bc2ca0bf7cc5c03b19",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "success": true,
                                            "data": {
                                                "token": "r6V74GKLmwYzFAbK2DWd31X1LMo8qj",
                                                "name": "Cleverson"
                                            },
                                            "message": "User login successfully"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/api/stocks/{symbol}": {
            "get": {
                "tags": [
                    "Stocks API"
                ],
                "description": "Search Stocks on API provider",
                "operationId": "25914a76a4244f7b2e88aee320608489",
                "parameters": [
                    {
                        "name": "symbol",
                        "in": "path",
                        "description": "Stocks name",
                        "required": true,
                        "examples": {
                            "string": {
                                "summary": "Netflix Stocks",
                                "value": "nflx"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "data": {
                                                "company_name": "Netflix Inc.",
                                                "symbol": "NFLX",
                                                "latest_price": 273.08
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Error",
                                        "value": {
                                            "error": "Enter a valid stock name"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/stocks/": {
            "get": {
                "tags": [
                    "Stocks"
                ],
                "description": "Get Searches history by user",
                "operationId": "c5b49062b2f866d15ce129dcb4fe4600",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "success": true,
                                            "data": {
                                                "id": 16,
                                                "user_id": 1,
                                                "company_name": "Netflix",
                                                "symbol": "nflx",
                                                "latest_price": "143.90",
                                                "created_at": "2022-11-03T17:47:03.000000Z",
                                                "updated_at": "2022-11-03T17:47:03.000000Z"
                                            },
                                            "message": "Recent searches"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Stocks"
                ],
                "description": "Search Stocks on API provider",
                "operationId": "2793f9a6c20bacfd948a5d1dc474a86d",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "company_name": {
                                        "type": "string"
                                    },
                                    "symbol": {
                                        "type": "string"
                                    },
                                    "latest_price": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "success": true,
                                            "data": {
                                                "id": 16,
                                                "user_id": 1,
                                                "company_name": "Netflix",
                                                "symbol": "nflx",
                                                "latest_price": "143.90",
                                                "created_at": "2022-11-03T17:47:03.000000Z",
                                                "updated_at": "2022-11-03T17:47:03.000000Z"
                                            },
                                            "message": "Stocks history created"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/stocks/{id}": {
            "delete": {
                "tags": [
                    "Stocks"
                ],
                "description": "Remove stocks search from history",
                "operationId": "eb7f842903e900a1a2ef85c471e4acd5",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Stocks id",
                        "required": true,
                        "examples": {
                            "integer": {
                                "summary": "Stocks id",
                                "value": "1"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "json"
                                        }
                                    ]
                                },
                                "examples": {
                                    "json": {
                                        "summary": "Sucess",
                                        "value": {
                                            "success": true,
                                            "data": {
                                                "id": 16,
                                                "user_id": 1,
                                                "company_name": "Netflix",
                                                "symbol": "nflx",
                                                "latest_price": "143.90",
                                                "created_at": "2022-11-03T17:47:03.000000Z",
                                                "updated_at": "2022-11-03T17:47:03.000000Z"
                                            },
                                            "message": "Stocks history deleted"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "apiAuth": {
                "type": "http",
                "description": "Bearer token",
                "name": "Token based Based",
                "in": "header",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}